USE Phone_E_Commerece_DB;

INSERT INTO THUONG_HIEU(TH_TEN) VALUES(N'iPhone');
INSERT INTO THUONG_HIEU(TH_TEN) VALUES(N'Xiaomi');
INSERT INTO THUONG_HIEU(TH_TEN) VALUES(N'SAMSUNG');
INSERT INTO THUONG_HIEU(TH_TEN) VALUES(N'NOKIA');
INSERT INTO THUONG_HIEU(TH_TEN) VALUES(N'Vsmart');