# Extension REST Client

# Mỗi Request cách nhau 3 dấu '#'


# -------------------------------- Default --------------------------------

# Tạo order

### Tạo order 201
POST http://localhost:8000/api/payments/default/createorder
Content-Type: application/json

{
    // Thông tin khác hàng
    "customer": {
    "cus_name": "Alexander",
    "cus_id": "555555555",
    "cus_email": "alex@gmail.com",
    "cus_sex": true,
    "cus_address": "3/2 Ninh Kiều Cần Thơ",
    "cus_phoneNumber": "0000000000"
    },

    // Mảng nhận id và số lượng
    "products":[
        {"prod_no": 1, "prod_quantity": 1, "pd_no": 1 },
        {"prod_no": 2, "prod_quantity": 1, "pd_no": 3}
    ]
}


### Thanh toán
GET http://localhost:8000/api/payments/default/checkoutorder/5d8e8403c4fbe51f04a30abbc68b3d79413b41a54a8d20c24b8f26952ec9ad1b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM0NDY5OTc3LCJleHAiOjE2MzQ0NzM1Nzd9.d1TDuqDvKFLzx6kEOFfaNPew_GzywMPaJGW4UOsLC2k



# -------------------------------- Paypal --------------------------------

# Lấy ra paypay client id - 200
GET http://localhost:8000/api/payments/paypal/clientid

### Tạo order - 201
POST http://localhost:8000/api/payments/paypal/createorder
Content-Type: application/json

{
    // Thông tin khác hàng
    "customer": {
    "cus_name": "Alexander",
    "cus_id": "555555555",
    "cus_email": "alex@gmail.com",
    "cus_sex": true,
    "cus_address": "3/2 Ninh Kiều Cần Thơ",
    "cus_phoneNumber": "0000000000"
    },
    
    // Mảng nhận id và số lượng
    "products":[
        {"prod_no": 1, "prod_quantity": 1, "pd_no": 1},
        {"prod_no": 2, "prod_quantity": 1, "pd_no": 3}
    ]
}


### Thanh toán
GET http://localhost:8000/api/payments/paypal/captureorder/6072225628845804W


# -------------------------------- Stripe --------------------------------

# Tạo order

### Tạo order 201
POST http://localhost:8000/api/payments/stripe/createorder?successUrl=http://localhost:3000&cancelUrl=http://localhost:3000
Content-Type: application/json

{
    // Thông tin khác hàng
    "customer": {
    "cus_name": "Alexander",
    "cus_id": "555555555",
    "cus_email": "alex@gmail.com",
    "cus_sex": true,
    "cus_address": "3/2 Ninh Kiều Cần Thơ",
    "cus_phoneNumber": "0000000000"
    },

    // Mảng nhận id và số lượng
    "products":[
        {"prod_no": 1, "prod_quantity": 1, "pd_no": 1 },
        {"prod_no": 2, "prod_quantity": 1, "pd_no": 3}
    ]
}


### Thanh toán
GET http://localhost:8000/api/payments/stripe/checkoutorder/7210a5e54e1b47c33073e703f1aac099332400f109432ccc815278b1052efe44?successUrl=http://localhost


# -------------------------------- ZaloPay --------------------------------

### Tạo order
POST http://localhost:8000/api/payments/zalo/createorder?successUrl=http://localhost:3000/success/zalo&cancelUrl=http://localhost:3000/cart
Content-Type: application/json

{
    // Thông tin khác hàng
    "customer": {
    "cus_name": "Alexander",
    "cus_id": "555555555",
    "cus_email": "alex@gmail.com",
    "cus_sex": true,
    "cus_address": "3/2 Ninh Kiều Cần Thơ",
    "cus_phoneNumber": "0000000000"
    },

    // Mảng nhận id và số lượng
    "products":[
        {"prod_no": 2, "prod_quantity": 1, "pd_no": 3}
    ]
}

### Thanh toán
GET http://localhost:8000/api/payments/zalo/checkoutorder/7210a5e54e1b47c33073e703f1aac099332400f109432ccc815278b1052efe44?url=http://localhost-http://localhost



# -------------------------------------------------------------------------

### Lấy ra order lưu tạm
GET http://localhost:8000/api/payments/storeorders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM0NzEzNTg0LCJleHAiOjE2MzQ3MTcxODR9.RjUHo_BlyRUrA3WElzKdXU8Fti4bqbDeMO86Vf2vSLU


### Lấy xóa order lưu tạm
DELETE http://localhost:8000/api/payments/storeorders/5cef8006b0e964a64f06c3bd57702b2de1217f953f3d61d79ed618cc3863543f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJyb2xlIjoiZW1wIn0sImlhdCI6MTYzNDI3OTg5MywiZXhwIjoxNjM0MjgzNDkzfQ.J5JGt-898DMMnbweMuVzAQGMa6-D4m6Owl0vJJEbRzQ



# -------------------------------------------------------------------------


### Lấy ra order đã thanh toán trong CSDL
GET http://localhost:8000/api/payments/getsaveorder/2

