
GET http://localhost:8000/api/products/1/feedbacks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjM0ODA0MTUzLCJleHAiOjE2MzQ4MDc3NTN9.i7qinbGnA_BeUiFQUif5rBI3exP57YZCFOWapGPx26E