# Extension REST Client

# Mỗi Request cách nhau 3 dấu '#'

# Mặc định page=1, limit=24
# Trang đầu không có previous, trang cuối không có next
GET http://localhost:8000/api/products?page=3&limit=3


# Truyền không hợp lệ trả về mặc định của số không hợp lệ
### 1 page không hợp lệ
GET http://localhost:8000/api/products?page=wtf&limit=1

### 2 limit không hợp lệ
GET http://localhost:8000/api/products?page=1&limit=wtf


# Lấy danh sách theo mức giá
### 1 Mặc định lấy tất
GET http://localhost:8000/api/products/price/

### 2 Lấy theo khoảng giá và số trang
GET http://localhost:8000/api/products/price/?min=41990000&max=44990000&page=1&limit=2


### 3 Min không phải số
GET http://localhost:8000/api/products/price/?min=wtf&max=44990000&page=1&limit=2

### 3 Max không phải số
GET http://localhost:8000/api/products/price/?min=41990000&max=wtf&page=1&limit=2





# ---------------------------------------------------------------------



### Lấy theo mã 200 
GET http://localhost:8000/api/products/1

# Không hợp lệ 400

### 1 mã không phải số
GET http://localhost:8000/api/products/wtf

### 2 mã âm
GET http://localhost:8000/api/products/-1

### 3 mã lớn hơn max int
GET http://localhost:8000/api/products/9007199254740992

### Không tồn tại 404
GET http://localhost:8000/api/products/9999



# ---------------------------------------------------------------------



### Lấy theo tên 200
GET http://localhost:8000/api/products/name/Galaxy Z Fold3 | Z Flip3 5G

# Không hợp lệ 400

### 1 độ dài tên < 5
GET http://localhost:8000/api/products/name/dt

### 2 độ dài tên > 50
GET http://localhost:8000/api/products/name/a8fad5592ed3d048090aa7d80fc2a4c4207fe936aeda98af429a

### Không tồn tại 404
GET http://localhost:8000/api/products/name/Xiaomi

###
GET  http://localhost:8000/api/products/price?min=0&max=60000000&page=1&limit=24



# ---------------------------------------------------------------------




# Thêm sản phẩm

### Samsung Galaxy Z Fold 3
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Galaxy Z Fold3 | Z Flip3 5G",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2021-8-1",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "Dynamic AMOLED 2X",
    "resolution": "Full HD+ (1768 x 2208 Pixels)",
    "size": "Chính 7.6' & Phụ 6.2' - Tần số quét 120 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass Victus"
  },
  "prod_camera": {
    "rear": {
      "spec": "3 camera 12 MP",
      "videoQuality":
        "4K 2160p@60fps, FullHD 1080p@240fps, FullHD 1080p@60fps, HD 720p@960fps"
    },
    "font": "10 MP & 4 MP 8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 888 8 nhân",
    "cpuSpec": "1 nhân 2.84 GHz, 3 nhân 2.42 GHz & 4 nhân 1.8 GHz",
    "gpu": "Adreno 660"
  },
  "prod_network": {
    "telecom": "5G",
    "SIM": "2 Nano Sim",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4400 mAh",
    "batteryType": "Li-ion",
    "chargeType": "25W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh viền" },
    { "Tính năng đặc biệt": "Samsung Pay Âm thanh AKG" },
    { "Kháng nước, bụi": "IPX8" }
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 158.2 mm - Ngang 128.1 mm - Dày 6.4 mm",
    "weight": "271 g"
  },
  "prod_status": "",
  "brand_no": 1
}

### iPhone 12 Pro Max
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "iPhone 12 Pro Max",
  "prod_manufacturer": {
    "brand_name": "Apple",
    "releaseDate": "2020-10",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "OLED",
    "resolution": "1284 x 2778 Pixels",
    "size": "6.7' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Ceramic Shield"
  },
  "prod_camera": {
    "rear": {
      "spec": "3 camera 12 MP",
      "videoQuality":"4K 2160p@30fps, 4K 2160p@60fps, FullHD 1080p@30fps, HD 720p@30fps, FullHD 1080p@60fps, 4K 2160p@24fps"
    },
    "font": "12 MP"
  },
  "prod_hardwareAndOS": {
    "os": "iOS 14",
    "cpu": "Apple A14 Bionic 6 nhân",
    "cpuSpec": "2 nhân 3.1 GHz & 4 nhân 1.8 GHz",
    "gpu": "Apple GPU 4 nhân"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "1 Nano SIM & 1 eSIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot, Dual-band (2.4 GHz/5 GHz)",
    "GPS": "BDS ,GLONASS, A-GPS",
    "Bluetooth": "A2DP, 5.0",
    "connector": "Lightning",
    "others": "Lightning"
  },
  "prod_batteryAndCharger": {
    "battery": "3687 mAh",
    "batteryType": "Li-ion",
    "chargeType": "20W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt Face ID" },
    { "Kháng nước, bụi": "IP68" },
    { "Ghi âm":"Có (microphone chuyên dụng chống ồn)"},
    { "Xem phim":"H.264(MPEG4-AVC)"},
    { "Nghe nhạc":"Lossless, AAC, MP3, FLAC"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung thép không gỉ & Mặt lưng kính cường lực",
    "size": "Dài 160.8 mm - Ngang 78.1 mm - Dày 7.4 mm",
    "weight": "228 g"
  },
  "prod_status": "",
  "brand_no": 2
}

### OPPO Reno6 Z 5G
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "OPPO Reno6 Z 5G",
  "prod_manufacturer": {
    "brand_name": "Oppo",
    "releaseDate": "2021-7",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.43' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Dimensity 800U 5G 8 nhân",
    "cpuSpec": "2 nhân 2.4 GHz & 6 nhân 2 GHz",
    "gpu": "Mali-G57 MC3"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS ,BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LE, v5.1",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4310 mAh",
    "batteryType": "Li-Po",
    "chargeType": "30W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay dưới màn hình" },
    { "Tính năng đặt biệt" :"Chạm 2 lần sáng màn hình, Ứng dụng kép (Nhân bản ứng dụng)" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"3GP, AVI, MP4, WMV"},
    { "Nghe nhạc":"AAC, AMR, MP3, WAV, WMA"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung hợp kim & Mặt lưng thuỷ tinh hữu cơ",
    "size": "Dài 160.2 mm - Ngang 73.38 mm - Dày 7.97 mm",
    "weight": "Nặng 173 g"
  },
  "prod_status": "",
  "brand_no": 3
}


### Xiaomi POCO X3 Pro NFC 8GB-256GB
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Xiaomi POCO X3 Pro NFC 8GB-256GB",
  "prod_manufacturer": {
    "brand_name": "Xiaomi",
    "releaseDate": "2021-4",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.67'",
    "glass": "Kính cường lực Corning Gorilla Glass 6"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 48 MP & Phụ 8 MP, 2 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, FullHD 1080p@30fps, FullHD 1080p@60fps"
    },
    "font": "20 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 860 8 nhân",
    "cpuSpec": "1 nhân 2.96 GHz, 3 nhân 2.42 GHz & 4 nhân 1.8 GHz",
    "gpu": "Adreno 640"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS ,BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LE, v5.0",
    "connector": "Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5160 mAh",
    "batteryType": "Li-Po",
    "chargeType": "33W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá vân tay" },
    { "Tính năng đặt biệt" :"Chạm 2 lần sáng màn hình, Ứng dụng kép (Nhân bản ứng dụng)" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"Có"},
    { "Nghe nhạc":"Có"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Đang cập nhật",
    "size": "Dài 165.3 mm - Ngang 76.8 mm - Dày 9.4 mm",
    "weight": "Nặng 215 g"
  },
  "prod_status": "",
  "brand_no": 4
}

### Xiaomi Redmi 10
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Xiaomi Redmi 10",
  "prod_manufacturer": {
    "brand_name": "Xiaomi",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 90 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 3"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 50 MP & Phụ 8 MP, 2 MP, 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio G88 8 nhân",
    "cpuSpec": "2 nhân 2.0 GHz & 6 nhân 1.8 GHz",
    "gpu": "Mali-G52 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS, BDS, GLONASS",
    "Bluetooth": "v5.1",
    "connector": "Type-C",
    "others": "Hồng ngoại, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "20W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    {"Tính năng đặc biệt":"Loa kép"},
    { "Kháng nước, bụi": "Không có" },
    { "Xem phim":"AVI, MP4"},
    { "Nghe nhạc":"FLAC, Midi, MP3, OGG"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa",
    "size": "Dài 161 mm - Ngang 75.53 mm - Dày 8.92 mm",
    "weight": "Nặng 181 g"
  },
  "prod_status": "",
  "brand_no": 4
}

### Nokia C30 3GB-32GB 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Nokia C30 3GB-32GB",
  "prod_manufacturer": {
    "brand_name": "Nokia",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.82' - Tần số quét 60 Hz",
    "glass": "Mặt kính cong 2.5D"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 13 MP & Phụ 2 MP",
      "videoQuality":"FullHD 1080p@30fpsHD, 720p@30fps"
    },
    "font": "5 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11 (Go Edition)",
    "cpu": "Spreadtrum SC9863A 8 nhân",
    "cpuSpec": "4 nhân 1.6 GHz & 4 nhân 1.2 GHz",
    "gpu": "IMG PowerVR GE8322"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n, Wi-Fi hotspot",
    "GPS":"A-GPS",
    "Bluetooth": "A2DP, v4.2",
    "connector": "Micro USB",
    "others": "Jack 3.5mm"
  },
  "prod_batteryAndCharger": {
    "battery": "6000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "10W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khóa bằng vân tay" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"MP4"},
    { "Nghe nhạc":"MP3, WAV"}
  ],
  "prod_design": {
    "structural": "Pin liền",
    "material": "Khung & Mặt lưng nhựa Polycarbonate",
    "size": "Dài 177.7 mm - Ngang 79.1 mm - Dày 9.9 mm",
    "weight": "Nặng 237 g"
  },
  "prod_status": "",
  "brand_no": 5
}

### Samsung Galaxy Note 20 Ultra
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Samsung Galaxy Note 20 Ultra",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2020-8",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "Dynamic AMOLED 2X",
    "resolution": "2K+ (1440 x 3088 Pixels)",
    "size": "6.9' - Tần số quét 120 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass Victus"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 108 MP & Phụ 12 MP, 12 MP, cảm biến Laser AF",
      "videoQuality":"8K 4320p@24fps"
    },
    "font": "10 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 10",
    "cpu": "Exynos 990 8 nhân",
    "cpuSpec": "2 nhân 2.73 GHz, 2 nhân 2.5 GHz & 4 nhân 2.0 Ghz",
    "gpu": "Mali-G77 MP11"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM hoặc 1 Nano SIM + 1 eSIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4500 mAh",
    "batteryType": "Li-ion",
    "chargeType": "25W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay dưới màn hình" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 164.8 mm - Ngang 77.2 mm - Dày 8.1 mm",
    "weight": "208 g"
  },
  "prod_status": "",
  "brand_no": 1
}

### Vsmart Aris
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Vsmart Aris",
  "prod_manufacturer": {
    "brand_name": "Vsmart",
    "releaseDate": "2018-1",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2340 Pixels)",
    "size": "6.39' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, HD 720p@240fps"
    },
    "font": "20 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 10",
    "cpu": "Snapdragon 730 8 nhân",
    "cpuSpec": "2 nhân 2.2 GHz & 6 nhân 1.8 GHz",
    "gpu": "Adreno 618"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac",
    "GPS": "A-GPS",
    "Bluetooth": "v5.0",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "18W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn, Trợ lý ảo Google Assistant, Ghi âm cuộc gọi, Ứng dụng kép (Nhân bản ứng dụng), Tối ưu game (Chế độ trò chơi), Ứng dụng kép, Không gian thứ hai (Không gian riêng tư)" },
    { "Kháng nước, bụi": "IP52" },
    {"Ghi âm": "Có"},
    {"Xem phim":"AVI, MP4"},
    {"Nghe nhạc": "AAC, AMR, FLAC, MP3, Midi, WAV"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung kim loại & Mặt lưng kính",
    "size": "Dài 156.2 mm - Ngang 75.04 mm - Dày 8.55 mm ",
    "weight": "178 g"
  },
  "prod_status": "",
  "brand_no": 6
}


### Samsung Galaxy A22 5G
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Samsung Galaxy A22 5G",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2021-6",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "TFT LCD",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.6' - Tần số quét 90 Hz",
    "glass": "Kính cường lực Corning Gorilla 4"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 48 MP & Phụ 5 MP, 2 MP",
      "videoQuality":"FullHD 1080p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Dimensity 700 5G 8 nhân",
    "cpuSpec": "2 nhân 2.2 GHz & 6 nhân 2.0 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 1
}

### iPhone XR
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "iPhone XR",
  "prod_manufacturer": {
    "brand_name": "Apple",
    "releaseDate": "2018-9",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "828 x 1792 Pixels",
    "size": "6.1' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Oleophobic (ion cường lực)"
  },
  "prod_camera": {
    "rear": {
      "spec": "12 MP",
      "videoQuality":"4K 2160p@30fps, 4K 2160p@60fps, FullHD 1080p@30fps, HD 720p@30fps, FullHD 1080p@60fps, 4K 2160p@24fps"
    },
    "font": "7 MP"
  },
  "prod_hardwareAndOS": {
    "os": "iOS 14",
    "cpu": "Apple A12 Bionic 6 nhân",
    "cpuSpec": "2 nhân 2.5 GHz & 4 nhân 1.6 GHz",
    "gpu": "Apple GPU 4 nhân"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "1 Nano SIM & 1 eSIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot, Dual-band (2.4 GHz/5 GHz)",
    "GPS": "BDS ,GLONASS, A-GPS",
    "Bluetooth": "A2DP, 5.0",
    "connector": "Lightning",
    "others": "Lightning, NFC"
  },
  "prod_batteryAndCharger": {
    "battery": "2942 mAh",
    "batteryType": "Li-ion",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt Face ID" },
    { "Tính năng đặc biệt": "Apple Pay"},
    { "Kháng nước, bụi": "IP67" },
    { "Ghi âm":"Có (microphone chuyên dụng chống ồn)"},
    { "Xem phim":"H.264(MPEG4-AVC)"},
    { "Nghe nhạc":"Lossless, AAC, MP3, FLAC"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 150.9 mm - Ngang 75.7 mm - Dày 8.3 mm",
    "weight": "194 g"
  },
  "prod_status": "",
  "brand_no": 2
}


### Vivo Y21
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Vivo Y21",
  "prod_manufacturer": {
    "brand_name": "Vivo",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.51' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 13 MP & Phụ 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio P35 8 nhân",
    "cpuSpec": "4 nhân 2.3 GHz & 4 nhân 1.8 GHz",
    "gpu": "IMG PowerVR GE8320"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot, Dual-band (2.4 GHz/5 GHz)",
    "GPS": "BDS ,GLONASS, A-GPS",
    "Bluetooth": "A2DP, 5.0",
    "connector": "Lightning",
    "others": "Lightning, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "18W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Xem phim":"3GP"},
    { "Nghe nhạc":"MP3"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa Polycarbonate",
    "size": "Dài 164.26 mm - Ngang 76.08 mm - Dày 8 mm",
    "weight": "182 g"
  },
  "prod_status": "",
  "brand_no": 7
}


### Điện thoại Samsung Galaxy A52s 5G
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Điện thoại Samsung Galaxy A52s 5G",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2021-9",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "Super AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 120 Hz",
    "glass": "Kính cường lực Corning Gorilla 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 1
}


### Realme C21y
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Realme C21y",
  "prod_manufacturer": {
    "brand_name": "Realme",
    "releaseDate": "2021-6",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.5' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 8
}


### OPPO A54 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "OPPO A54",
  "prod_manufacturer": {
    "brand_name": "Oppo",
    "releaseDate": "2021-7",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.43' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Dimensity 800U 5G 8 nhân",
    "cpuSpec": "2 nhân 2.4 GHz & 6 nhân 2 GHz",
    "gpu": "Mali-G57 MC3"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS ,BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LE, v5.1",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4310 mAh",
    "batteryType": "Li-Po",
    "chargeType": "30W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay dưới màn hình" },
    { "Tính năng đặt biệt" :"Chạm 2 lần sáng màn hình, Ứng dụng kép (Nhân bản ứng dụng)" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"3GP, AVI, MP4, WMV"},
    { "Nghe nhạc":"AAC, AMR, MP3, WAV, WMA"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung hợp kim & Mặt lưng thuỷ tinh hữu cơ",
    "size": "Dài 160.2 mm - Ngang 73.38 mm - Dày 7.97 mm",
    "weight": "Nặng 173 g"
  },
  "prod_status": "",
  "brand_no": 3
}

### Samsung Galaxy S20 FE
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Samsung Galaxy S20 FE",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2021-9",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "Super AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 120 Hz",
    "glass": "Kính cường lực Corning Gorilla 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 1
}


### Xiaomi Redmi Note 10S
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Xiaomi Redmi Note 10S",
  "prod_manufacturer": {
    "brand_name": "Xiaomi",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 90 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 3"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 50 MP & Phụ 8 MP, 2 MP, 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio G88 8 nhân",
    "cpuSpec": "2 nhân 2.0 GHz & 6 nhân 1.8 GHz",
    "gpu": "Mali-G52 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS, BDS, GLONASS",
    "Bluetooth": "v5.1",
    "connector": "Type-C",
    "others": "Hồng ngoại, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "20W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    {"Tính năng đặc biệt":"Loa kép"},
    { "Kháng nước, bụi": "Không có" },
    { "Xem phim":"AVI, MP4"},
    { "Nghe nhạc":"FLAC, Midi, MP3, OGG"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa",
    "size": "Dài 161 mm - Ngang 75.53 mm - Dày 8.92 mm",
    "weight": "Nặng 181 g"
  },
  "prod_status": "",
  "brand_no": 4
}

### Vivo Y12s
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Vivo Y12s",
  "prod_manufacturer": {
    "brand_name": "Vivo",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.51' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 13 MP & Phụ 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio P35 8 nhân",
    "cpuSpec": "4 nhân 2.3 GHz & 4 nhân 1.8 GHz",
    "gpu": "IMG PowerVR GE8320"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot, Dual-band (2.4 GHz/5 GHz)",
    "GPS": "BDS ,GLONASS, A-GPS",
    "Bluetooth": "A2DP, 5.0",
    "connector": "Lightning",
    "others": "Lightning, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "18W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Xem phim":"3GP"},
    { "Nghe nhạc":"MP3"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa Polycarbonate",
    "size": "Dài 164.26 mm - Ngang 76.08 mm - Dày 8 mm",
    "weight": "182 g"
  },
  "prod_status": "",
  "brand_no": 7
}

### Realme C20
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Realme C20",
  "prod_manufacturer": {
    "brand_name": "Realme",
    "releaseDate": "2021-6",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.5' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 8
}

### Vivo V21 5G
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Vivo V21 5G",
  "prod_manufacturer": {
    "brand_name": "Vivo",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.51' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 13 MP & Phụ 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio P35 8 nhân",
    "cpuSpec": "4 nhân 2.3 GHz & 4 nhân 1.8 GHz",
    "gpu": "IMG PowerVR GE8320"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot, Dual-band (2.4 GHz/5 GHz)",
    "GPS": "BDS ,GLONASS, A-GPS",
    "Bluetooth": "A2DP, 5.0",
    "connector": "Lightning",
    "others": "Lightning, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "18W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Xem phim":"3GP"},
    { "Nghe nhạc":"MP3"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa Polycarbonate",
    "size": "Dài 164.26 mm - Ngang 76.08 mm - Dày 8 mm",
    "weight": "182 g"
  },
  "prod_status": "",
  "brand_no": 7
}


### Xiaomi Redmi 9C 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Xiaomi Redmi 9C ",
  "prod_manufacturer": {
    "brand_name": "Xiaomi",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 90 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 3"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 50 MP & Phụ 8 MP, 2 MP, 2 MP",
      "videoQuality":"FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "8 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Helio G88 8 nhân",
    "cpuSpec": "2 nhân 2.0 GHz & 6 nhân 1.8 GHz",
    "gpu": "Mali-G52 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS, BDS, GLONASS",
    "Bluetooth": "v5.1",
    "connector": "Type-C",
    "others": "Hồng ngoại, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "20W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    {"Tính năng đặc biệt":"Loa kép"},
    { "Kháng nước, bụi": "Không có" },
    { "Xem phim":"AVI, MP4"},
    { "Nghe nhạc":"FLAC, Midi, MP3, OGG"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung & Mặt lưng nhựa",
    "size": "Dài 161 mm - Ngang 75.53 mm - Dày 8.92 mm",
    "weight": "Nặng 181 g"
  },
  "prod_status": "",
  "brand_no": 4
}

### Realme 8
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Realme 8",
  "prod_manufacturer": {
    "brand_name": "Realme",
    "releaseDate": "2021-6",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.5' - Tần số quét 60 Hz",
    "glass": "Kính cường lực"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 8
}


### OPPO A74 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "OPPO A74",
  "prod_manufacturer": {
    "brand_name": "Oppo",
    "releaseDate": "2021-7",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.43' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Dimensity 800U 5G 8 nhân",
    "cpuSpec": "2 nhân 2.4 GHz & 6 nhân 2 GHz",
    "gpu": "Mali-G57 MC3"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS ,BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LE, v5.1",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4310 mAh",
    "batteryType": "Li-Po",
    "chargeType": "30W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay dưới màn hình" },
    { "Tính năng đặt biệt" :"Chạm 2 lần sáng màn hình, Ứng dụng kép (Nhân bản ứng dụng)" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"3GP, AVI, MP4, WMV"},
    { "Nghe nhạc":"AAC, AMR, MP3, WAV, WMA"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung hợp kim & Mặt lưng thuỷ tinh hữu cơ",
    "size": "Dài 160.2 mm - Ngang 73.38 mm - Dày 7.97 mm",
    "weight": "Nặng 173 g"
  },
  "prod_status": "",
  "brand_no": 3
}

### Nokia 5.4 
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Nokia 5.4",
  "prod_manufacturer": {
    "brand_name": "Nokia",
    "releaseDate": "2021-8",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "IPS LCD",
    "resolution": "HD+ (720 x 1600 Pixels)",
    "size": "6.82' - Tần số quét 60 Hz",
    "glass": "Mặt kính cong 2.5D"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 13 MP & Phụ 2 MP",
      "videoQuality":"FullHD 1080p@30fpsHD, 720p@30fps"
    },
    "font": "5 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11 (Go Edition)",
    "cpu": "Spreadtrum SC9863A 8 nhân",
    "cpuSpec": "4 nhân 1.6 GHz & 4 nhân 1.2 GHz",
    "gpu": "IMG PowerVR GE8322"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Wi-Fi 802.11 a/b/g/n, Wi-Fi hotspot",
    "GPS":"A-GPS",
    "Bluetooth": "A2DP, v4.2",
    "connector": "Micro USB",
    "others": "Jack 3.5mm"
  },
  "prod_batteryAndCharger": {
    "battery": "6000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "10W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khóa bằng vân tay" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"MP4"},
    { "Nghe nhạc":"MP3, WAV"}
  ],
  "prod_design": {
    "structural": "Pin liền",
    "material": "Khung & Mặt lưng nhựa Polycarbonate",
    "size": "Dài 177.7 mm - Ngang 79.1 mm - Dày 9.9 mm",
    "weight": "Nặng 237 g"
  },
  "prod_status": "",
  "brand_no": 5
}


### Samsung Galaxy S20 Ultra
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "Samsung Galaxy S20 Ultra",
  "prod_manufacturer": {
    "brand_name": "Samsung",
    "releaseDate": "2021-9",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "Super AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.5' - Tần số quét 120 Hz",
    "glass": "Kính cường lực Corning Gorilla 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
      "videoQuality":" 4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@240fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "Snapdragon 778G 5G 8 nhân",
    "cpuSpec": "1 nhân 2.4 GHz, 3 nhân 2.2 GHz & 4 nhân 1.9 GHz",
    "gpu": "Mali-G57 MC2"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi Direct, Wi-Fi hotspot",
    "GPS": "A-GPS, BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LEv, 5.2",
    "connector": "2 đầu Type-C",
    "others": "NFC, OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "5000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "15W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá vân tay cạnh" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn ,Màn hình luôn hiển thị AOD, Samsung DeX (Kết nối màn hình sử dụng giao diện tương tự PC) ,Samsung Pay,Trợ lý ảo Samsung Bixby, Âm thanh AKG, Âm thanh Dolby Audio" },
    { "Kháng nước, bụi": "IP68" },
    {"Ghi âm": "Có (microphone chuyên dụng chống ồn)"},
    {"Xem phim":"3GP, AVI, DivX, H.263, H.264(MPEG4-AVC), H.265, MP4, Xvid"},
    {"Nghe nhạc": "AAC++, AMR, FLAC, MP3, Midi, WAV, eAAC+"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung nhôm & Mặt lưng kính cường lực",
    "size": "Dài 167.2 mm - Ngang 76.4 mm - Dày 9 mm ",
    "weight": "203 g"
  },
  "prod_status": "",
  "brand_no": 1
}


### OPPO Find X3 Pro
POST http://localhost:8000/api/products/
Content-Type: application/json

{
  "prod_name": "OPPO Find X3 Pro",
  "prod_manufacturer": {
    "brand_name": "Oppo",
    "releaseDate": "2021-7",
    "madeIn": "Trung Quốc"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2400 Pixels)",
    "size": "6.43' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, FullHD 1080p@30fps, HD 720p@30fps"
    },
    "font": "32 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 11",
    "cpu": "MediaTek Dimensity 800U 5G 8 nhân",
    "cpuSpec": "2 nhân 2.4 GHz & 6 nhân 2 GHz",
    "gpu": "Mali-G57 MC3"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 5G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi Direct, Wi-Fi hotspot",
    "GPS":"A-GPS ,BDS, GALILEO, GLONASS",
    "Bluetooth": "A2DP, LE, v5.1",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4310 mAh",
    "batteryType": "Li-Po",
    "chargeType": "30W"
  },
  "prod_utilities": [
    { "Bảo mật nâng cao": "Mở khoá khuôn mặt, Mở khoá vân tay dưới màn hình" },
    { "Tính năng đặt biệt" :"Chạm 2 lần sáng màn hình, Ứng dụng kép (Nhân bản ứng dụng)" },
    { "Kháng nước, bụi": "Không có" },
    { "Ghi âm":"Có"},
    { "Raido": "Có" },
    { "Xem phim":"3GP, AVI, MP4, WMV"},
    { "Nghe nhạc":"AAC, AMR, MP3, WAV, WMA"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung hợp kim & Mặt lưng thuỷ tinh hữu cơ",
    "size": "Dài 160.2 mm - Ngang 73.38 mm - Dày 7.97 mm",
    "weight": "Nặng 173 g"
  },
  "prod_status": "",
  "brand_no": 3
}



# ---------------------------------------------------------------------

# Sửa sản phẩm

### Hợp lệ
PUT http://localhost:8000/api/products/8
Content-Type: application/json

{
  "prod_name": "Vsmart Aris",
  "prod_manufacturer": {
    "brand_name": "Vsmart",
    "releaseDate": "2018-1",
    "madeIn": "Việt Nam"
  },
  "prod_screen": {
    "type": "AMOLED",
    "resolution": "Full HD+ (1080 x 2340 Pixels)",
    "size": "6.39' - Tần số quét 60 Hz",
    "glass": "Kính cường lực Corning Gorilla Glass 5"
  },
  "prod_camera": {
    "rear": {
      "spec": "Chính 64 MP & Phụ 8 MP, 8 MP, 2 MP",
      "videoQuality":"4K 2160p@30fps, HD 720p@240fps"
    },
    "font": "20 MP"
  },
  "prod_hardwareAndOS": {
    "os": "Android 10",
    "cpu": "Snapdragon 730 8 nhân",
    "cpuSpec": "2 nhân 2.2 GHz & 6 nhân 1.8 GHz",
    "gpu": "Adreno 618"
  },
  "prod_network": {
    "telecom": "Hỗ trợ 4G",
    "SIM": "2 Nano SIM",
    "Wifi": "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac",
    "GPS": "A-GPS",
    "Bluetooth": "v5.0",
    "connector": "Type-C",
    "others": "OTG"
  },
  "prod_batteryAndCharger": {
    "battery": "4000 mAh",
    "batteryType": "Li-Po",
    "chargeType": "18W"
  },
  "prod_utilities": [
    { "Bảo mật": "Mở khoá khuôn mặt, Mở khoá vân tay cạnh viền" },
    { "Tính năng đặc biệt": "Chặn cuộc gọi, Chặn tin nhắn, Trợ lý ảo Google Assistant, Ghi âm cuộc gọi, Ứng dụng kép (Nhân bản ứng dụng), Tối ưu game (Chế độ trò chơi), Ứng dụng kép, Không gian thứ hai (Không gian riêng tư)" },
    { "Kháng nước, bụi": "IP52" },
    {"Ghi âm": "Có"},
    {"Xem phim":"AVI, MP4"},
    {"Nghe nhạc": "AAC, AMR, FLAC, MP3, Midi, WAV"}
  ],
  "prod_design": {
    "structural": "Nguyên khối",
    "material": "Khung kim loại & Mặt lưng kính",
    "size": "Dài 156.2 mm - Ngang 75.04 mm - Dày 8.55 mm ",
    "weight": "178 g"
  },
  "prod_status": "",
  "brand_no": 6
}

