# Extension REST Client

GET http://localhost:8000/api/notes?page=2&limit=5

# Lấy theo mã 
### products/1
GET http://localhost:8000/api/notes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA5MTc4MDcsImV4cCI6MTYzMDkyMTQwN30.PaOHc1xoCV6Q1vmWPzig1h2QiDwtl3YTYpTLpcRIZtk


# Mã không hợp lệ
### 1
GET http://localhost:8000/api/notes/wtf

### 2
GET http://localhost:8000/api/notes/-1