# Extension REST Client

GET http://localhost:8000/api/notes?page=2&limit=5

# Lấy theo mã 
### products/1
GET http://localhost:8000/api/notes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA5ODA5NTgsImV4cCI6MTYzMDk4NDU1OH0.vCzxrGYNrDr_CFazXu-sdhL-QtxMRAhB3oZY8en6yNs


# Mã không hợp lệ
### 1
GET http://localhost:8000/api/notes/wtf

### 2
GET http://localhost:8000/api/notes/-1


### Thêm
POST http://localhost:8000/api/notes
Content-Type: application/json

{
    "id": 1,
    "title": "alex",
    "content": "nội dung"
}